name: Selenium Automation Tests

on:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Selenium Tests
        run: mvn clean test -Dheadless=true
